{
 "title": "Linux Event Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"rule_groups:*linux*\"}\n"
   }
  ]
 },
 "panels": [
  { "title": "LINUX EVENT LOGS - PROCESS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LINUX SYSTEM - EVENTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:50",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:1 OR data_system_eventId:4 OR data_system_eventId:5 OR data_system_eventId:9)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LINUX SYSTEM - EVENTS BY TYPE",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:3082",
       "fake": true,
       "field": "rule_description",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "rule_level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:1 OR data_system_eventId:4 OR data_system_eventId:5 OR data_system_eventId:9)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LINUX SYSTEM - EVENTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:73",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:1 OR data_system_eventId:4 OR data_system_eventId:5 OR data_system_eventId:9)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LINUX SYSTEM - EVENTS BY AGENT (HISTOGRAM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:1 OR data_system_eventId:4 OR data_system_eventId:5 OR data_system_eventId:9)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LINUX SYSTEM - EVENTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:1 OR data_system_eventId:4 OR data_system_eventId:5 OR data_system_eventId:9)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LINUX EVENT LOGS - NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "LINUX NETWORK - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_groups:*linux* AND agent_name:$agent_name AND data_system_eventId:3) OR (rule_groups:*suricata*)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX NETWORK - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_groups:*linux* AND agent_name:$agent_name AND data_system_eventId:3) OR (rule_groups:*suricata*)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX NETWORK - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_groups:*linux* AND agent_name:$agent_name AND data_system_eventId:3) OR (rule_groups:*suricata*)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX NETWORK - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "(rule_groups:*linux* AND agent_name:$agent_name AND data_system_eventId:3) OR (rule_groups:*suricata*)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX NETWORK - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "(rule_groups:*linux* AND agent_name:$agent_name AND data_system_eventId:3) OR (rule_groups:*suricata*)",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "LINUX EVENT LOGS - FILES ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "LINUX FILES - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:11 OR data_system_eventId:16 OR data_system_eventId:23)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX FILES - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:11 OR data_system_eventId:16 OR data_system_eventId:23)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX FILESS - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:2063",
         "fake": true,
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:11 OR data_system_eventId:16 OR data_system_eventId:23)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX FILES - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:11 OR data_system_eventId:16 OR data_system_eventId:23)",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "LINUX FILES - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule_groups:*linux* AND agent_name:$agent_name AND (data_system_eventId:11 OR data_system_eventId:16 OR data_system_eventId:23)",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}