{
 "title": "MITRE ATT&CK",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters", "label": "Filters" },
   {
    "name": "agent_name",
    "label": "AGENT",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"_exists_:rule_mitre_tactic\"}"
   },
   {
    "name": "mitre_id",
    "label": "Mitre ID",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_mitre_id\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "MITRE ATT&CK EBRICHMENT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "MITRE ENRICHED EVENTS",
     "bucketAggs": [
      {
       "$$hashKey": "object:266",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:264", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:rule_mitre_tactic AND agent_name:$agent_name AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    },
    {
     "alias": "ALL EVENTS",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK ALERTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:266",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:264", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule_level:>=12 AND _exists_:rule_mitre_tactic AND agent_name:$agent_name AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HOSTS AFFECTED",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:161",
       "field": "agent_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:159",
       "field": "agent_name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "rule_level:>=12 AND _exists_:rule_mitre_tactic AND agent_name:$agent_name AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HOSTS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:188",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:189",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:186", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:rule_mitre_tactic AND agent_name:$agent_name AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USERS/ACCOUNTS AFFECTED",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:228",
       "field": "user_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:226",
       "field": "user_name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "_exists_:rule_mitre_tactic AND agent_name:$agent_name AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TACTICS (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:82",
       "fake": true,
       "field": "rule_mitre_tactic",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:83",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK ID",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 5, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:615",
       "fake": true,
       "field": "rule_mitre_id",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LOG VIEWER",
   "type": "logs",
   "gridPos": { "h": 22, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "agent_name:$agent_name AND (_exists_:rule_mitre_tactic OR _exists_:data_win_eventdata_ruleName) AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:82",
       "fake": true,
       "field": "rule_mitre_technique",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:83",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND (_exists_:rule_mitre_tactic OR _exists_:data_win_eventdata_ruleName) AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK TECHNIQUES",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 5, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:615",
       "fake": true,
       "field": "rule_mitre_technique",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND (_exists_:rule_mitre_tactic OR _exists_:data_win_eventdata_ruleName) AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - TOP 10 AGENTS",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:82",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:80", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND (_exists_:rule_mitre_tactic OR _exists_:data_win_eventdata_ruleName) AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - HISTOGRAM",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:644",
       "fake": true,
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:627",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:625", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND (_exists_:rule_mitre_tactic OR _exists_:data_win_eventdata_ruleName) AND rule_mitre_id:$mitre_id",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MITRE ATT&CK - TELEMETRY",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "agent_name:$agent_name AND (_exists_:rule_mitre_tactic OR _exists_:data_win_eventdata_ruleName) AND rule_mitre_id:$mitre_id NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}