{
 "title": "Summary Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"client_group:$client_group\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_level\", \"query\": \"client_group:$client_group\"}"
   },
   { "name": "Filters" },
   {
    "name": "client_group",
    "label": "Client Group",
    "query": "{ \"find\": \"terms\", \"field\": \"client_group\", \"query\": \"\"}"
   },
   {
    "name": "zabbix_group",
    "label": "zabbix group",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "AGENTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "agent_name", "id": "1", "type": "cardinality" }
     ],
     "query": "agent_name:$agent_name AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_level:>=11",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS - DETAILS",
   "type": "logs",
   "gridPos": { "h": 21, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "1000" }, "type": "logs" }
     ],
     "query": "(syslog_level:ALERT OR rule_level:>=8) AND agent_name:$agent_name AND rule_level:$rule_level AND client_group:$client_group",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:>=8 AND rule_level:<=11 AND agent_name:$agent_name AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS (TOTAL)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MAX SEVERITY (0 - 15)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rule_level", "id": "1", "type": "max" }
     ],
     "query": "agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Contego" },
     "host": { "filter": "SIEM - CONTEGO" },
     "item": { "filter": "Index CONTEGO" },
     "itemTag": { "filter": "SIEM: CONTEGO" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ALERTS BY CATEGORY",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_description",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "agent_name:$agent_name AND rule_level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "LOCATIONS",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst_ip",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "geoip_latitude",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "geoip_longitude",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "(rule_groups:*sysmon_event3* OR rule_groups:*sysmon_eid3_detections*) AND agent_name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}