{
 "title": "Users And Groups",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"(rule_groups:*windows_system* OR rule_groups:*windows_application* OR rule_group:*windows_security* OR rule_groups:*policy_changed*)\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "USER ACCOUNTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ACCOUNTS CREATED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4720",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNTS CREATED",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_targetUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4720",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNTS LOCKED OUT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4740",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNTS LOCKED OUT",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_targetUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4740",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNTS MODIFIED",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4738",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNTS MODIFIED",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_targetUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4738",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNT PASSWORD CHANGES",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4723 OR data_win_system_eventID:4724",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ACCOUNT PASSWORD CHANGES",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_subjectUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4723 OR data_win_system_eventID:4724",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USER ACCOUNTS - EVENTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "(data_win_system_eventID:4720 OR data_win_system_eventID:4740 OR data_win_system_eventID:4738 OR data_win_system_eventID:4723 OR data_win_system_eventID:4728 OR data_win_system_eventID:4732 OR data_win_system_eventID:4756) AND agent_name:$agent_name NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "USER GROUPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "GROUPS CREATED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4727 OR data_win_system_eventID:4731",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GROUPS ADDED",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_targetUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4727 OR data_win_system_eventID:4731",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GROUPS MODIFIED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4764 OR data_win_system_eventID:4734 OR data_win_system_eventID:4735",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "GROUPS MODIFIED",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_targetUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4764 OR data_win_system_eventID:4734 OR data_win_system_eventID:4735",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MODIFIED PRIVILEGE GROUPS",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_targetUserName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data_win_system_eventID:4728 OR data_win_system_eventID:4732 OR data_win_system_eventID:4756",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "USER GROUPS - EVENTS",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "(data_win_system_eventID:4727 OR data_win_system_eventID:4731 OR data_win_system_eventID:4764 OR data_win_system_eventID:4728 OR data_win_system_eventID:4732 OR data_win_system_eventID:4733 OR data_win_system_eventID:4734 OR data_win_system_eventID:4735 OR data_win_system_eventID:4764 OR data_win_system_eventID:4799 OR data_win_system_eventID:4756) AND agent_name:$agent_name NOT rule_id:60109",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}