{
 "title": "Windows Event Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"(rule_groups:*windows_system* OR rule_groups:*windows_application* OR rule_groups:*windows_security* OR rule_groups:*windows_logonsessions* OR rule_groups:*policy_changed* OR rule_groups:*software_policy*)\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "WINDOWS EVENT LOGS - SYSTEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "WINDOWS SYSTEM - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_system* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SYSTEM - SEVERITY LEVELS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_win_system_severityValue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_system* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SYSTEM - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_system* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SYSTEM - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_system* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SYSTEM - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_system* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SYSTEM - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule_groups:*windows_system* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "WINDOWS EVENT LOGS - APPLICATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "WINDOWS APPLICATIONS - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_application* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS APPLICATIONS - SEVERITY LEVELS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_win_system_severityValue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_application* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS APPLICATIONS - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_application* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS APPLICATIONS - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "agent_name",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_application* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS APPLICATIONS - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_application* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS APPLICATIONS - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule_groups:*windows_application* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "WINDOWS EVENT LOGS - SECURITY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "WINDOWS SECURITY - EVENTS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - SEVERITY LEVELS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_win_system_severityValue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - EVENTS BY TYPE",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - EVENTS BY AGENT",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:2063",
         "fake": true,
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - EVENTS BY AGENT (HISTOGRAM)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "agent_name",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        { "field": "timestamp", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - AUTH TYPES",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_win_eventdata_authenticationPackageName",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - AUTH TYPES",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:2063",
         "fake": true,
         "field": "data_win_eventdata_authenticationPackageName",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - ACCOUNTS",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:3082",
         "fake": true,
         "field": "data_win_eventdata_subjectUserName",
         "id": "4",
         "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "rule_level",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "WINDOWS SECURITY - EVENTS",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule_groups:*windows_security* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "WINDOWS GROUP POLICY CHANGES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "GP CHANGES",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:50",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:48", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*policy_changed* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GP CHANGES - EVENT SEVERITY",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_win_system_severityValue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*policy_changed* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GP CHANGES - PROVIDER NAME",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:73",
         "fake": true,
         "field": "data_win_system_providerName",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:74",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*policy_changed* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GP CHANGES - EVENT DESCRIPTION",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:2063",
         "fake": true,
         "field": "rule_description",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "$$hashKey": "object:71", "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "rule_groups:*policy_changed* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "GP CHANGES - EVENTS",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "rule_groups:*policy_changed* AND agent_name:$agent_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}